### ISSUE TITLE
Add CLI Using __main__.py

### ISSUE THREAD

**Issue by grantjenks** [hsoft/send2trash#15]
Great project. I wish this functionality were included in the standard library. Thank you.

I'm curious how the methodology here compares with this JavaScript package: https://github.com/sindresorhus/trash

If you have time, what are your thoughts?

**Comment by hsoft** [comment]
First of all, it uses pre-compiled libraries for macos and windows. That doesn't seem like a good idea. send2trash links to core APIs directly.

For linux, I'm guessing it does the right thing, assuming that `xdg-trashdir` is properly implemented.

**Comment by grantjenks** [comment]
I agree! I hadn't found the source for those. Now I see them. Couple of differences I noticed:

In the Windows C-version at https://github.com/sindresorhus/recycle-bin/blob/master/recycle-bin.c the flags used are "FOF_ALLOWUNDO | FOF_NO_UI" but you're using "FOF_ALLOWUNDO | FOF_NOCONFIRMATION | FOF_NOERRORUI | FOF_SILENT" which according to https://msdn.microsoft.com/en-us/library/windows/desktop/bb759795(v=vs.85).aspx omits FOF_NOCONFIRMMKDIR. You might want to add that?

In the OSX C-version at https://github.com/sindresorhus/macos-trash/blob/master/trash.m the NSFileManager's trashItemAtURL is used. But you're using CoreServices' FSMoveObjectToTrashSync. Is there a particular reason for the difference? Maybe Cocoa support? (I'm not much of a Mac developer.)

Last thought: there's a trash-cli at https://github.com/sindresorhus/trash-cli based on the JS trash repo. I think it would be pretty easy to add a similar CLI interface. Would you consider adding such an interface?

**Comment by hsoft** [comment]
FOF_NOCONFIRMMKDIR: if it fixes a real problem, yes, sure.

OSX: send2trash uses `ctypes` to avoid having to compile anything on machines it installs itself on. We can't just compile a bridge with objc code. It's much easier to call `FSMoveObjectToTrashSync` from `ctypes` than to send an objc message through cocoa's C API. I'm sure it's possible, I just haven't done it.

CLI: `send2trash` users expect this to be a library, they don't expect their `bin` folder to be polluted with stuff. It's much better if it's a separate project.

**Comment by grantjenks** [comment]
Regarding the CLI, I'm not asking you to pollute the bin directory. You can simply add __main__.py and then give users a CLI like "python -m send2trash filename.txt". Would you accept a pull request with that addition?

**Comment by hsoft** [comment]
@grantjenks Wading through open issues, I realize that I never answer your last question. Sorry about that, it wasn't intentional. The answer is "yes", of course.

**Comment by NMertsch** [comment]
Hi, I don't want to necropost, but are there intentions to merge this?
