### ISSUE TITLE
Fails with python 3.6.3 on windows

### ISSUE THREAD

**Issue by rkhwaja** [hsoft/send2trash#17]
I get the following when calling send2trash on python 3.6.3 on windows 7:
`File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\send2trash\plat_win.py", line 49, in send2trash
fileop.pFrom = LPCWSTR(path + '\0')
ValueError: embedded null character
`

I'm pretty sure it didn't fail until I switched to 3.6.3. My guess is that [this](https://bugs.python.org/issue23908) fix is responsible.

**Comment by hsoft** [comment]
Thanks for the report. I don't use Windows, however, so I'll have to rely on a PR from someone else.

Something tells me that simply removing that `+ '\0'` will break stuff, but I can't remember why it's there.

**Comment by rkhwaja** [comment]
Yes - I tried that and the win32 call itself returns an error (87 - invalid parameter) - probably because it's expecting a null-terminated string???

**Comment by hsoft** [comment]
Oh, I remember: `pFrom` has to be [double nul terminated](https://msdn.microsoft.com/en-us/library/windows/desktop/bb759795(v=vs.85).aspx). I don't know how we'll go around that...

**Comment by asweigart** [comment]
Is this a problem with certain file names or files with certain content? I'm trying to recreate this issue on Windows 7 with Python 3.6.2 using send2trash 1.4.1 but can't. Can you post the file you are trying to delete? I'm on Windows and could take a look at this issue.

**Comment by rkhwaja** [comment]
It's only on Python 3.6.3.

**Comment by arsenetar** [comment]
It is definitely a 3.6.3 (over 3.6.2) issue, there is a possible work-around I have found, but I need to verify that it works as expected reliably.  If you want to reproduce the issue on windows all you need to do is:

```python
from send2trash import send2trash
send2trash('pathtosomefile')
```
Workaround uses `ctypes` functions to create a buffer and write the null characters into the buffer then  use a LPWSTR() cast on the address of the buffer.  It seems to work in initial tests.  Putting the code inline yeilds:

```python
from ctypes import create_unicode_buffer, addressof
from ctypes.wintypes import LPWSTR
# create buffer of c_wchar[] LPCWSTR is based on this type
# uses length of string + space for two null termination characters
buffer = create_unicode_buffer(path, len(path)+2)
# explicitly set the last two characters
# (not sure if it is possible for them to be non null at this point
buffer[len(path)] = '\0'
buffer[len(path)+1] = '\0'
fileop.pFrom = LPWSTR(addressof(buffer))
```

I will try getting around to some more verification work but this seems to be working.

**Comment by hsoft** [comment]
@arsenetar this looks like a good workaround. If you say it works, then I say we go for it. Could you please add a comment with a link to this issue in it? Future readers might not understand the purpose of this.

**Comment by arsenetar** [comment]
@hsoft Yeah I can added that comment information. I would like to look into create_unicode_buffer() to see if the two buffer[index] = '\0' lines are redundant as I have only seen null characters in them at this point.

**Comment by hsoft** [comment]
@rkhwaja could you please confirm the fix?

**Comment by rkhwaja** [comment]
Works great - thanks.

**Comment by MagTun** [comment]
Just for the latecomers like me, upgrading to version `1.5.0` fixed it:  
`pip install 'send2trash==1.5.0' `
