### ISSUE TITLE
Importing a bad library version on macOS and Python 3.6

### ISSUE THREAD

**Issue by BoboTiG** [hsoft/send2trash#29]
[This code](https://github.com/hsoft/send2trash/blame/master/send2trash/plat_osx.py#L14) is quite old :)

We have an application that uses the module on Python 3.6.6. We have installed [pyobjc](https://pypi.org/project/pyobjc-framework-Cocoa/#files) 4.2.2 that proposes different wheels depending the macOS version. So we are on macOS > 10.9.

The file pointed has a "misuse" of the `ctype.util.find_library()` function, in fact it returns a bad framework version:
```python
>>> Foundation = cdll.LoadLibrary(find_library('Foundation'))
>>> find_library('Foundation')
/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation (Python 2.7)
```

The fix is simple:
```python
>>> import Foundation
>>> Foundation.__path__
['/.../lib/python3.6/site-packages/Foundation']
```
But then, as you are using obsolete and removed functions, the entire content of `plat_osx.py` fails.

The error is even worse when packaging the application with PyInstaller (which isolate the final executable from the OS), and so it never finds a library. Moreover, `find_libary()` works with predefined search paths and patterns, it will never find the good file.

How do you want to deal with the issue? Perhaps can I try to fix it and send a PR or perhaps have you already clues/started something from your side?

**Comment by hsoft** [comment]
I don't quite remember everything about OS X, but we seem to be talking about two different things here: pyobj'c Foundation and the *real* Foundation.

`send2trash` does not depend on pyobjc. That is why it loads Foundation through `ctypes`, not through `import Foundation`.

That it fails on recent macos is possible, though certainly not as far back as macos 10.9. if often tested send2trash on macos with python 3 until I stopped using my mac entirely, and it was mac os 10.11.

**Comment by BoboTiG** [comment]
Hm you are right :)

I find the root cause and it was a missing symlink after PyInstaller packaging.

Thanks for your time.
