### ISSUE TITLE
File not move to Recycle Bin in Windows

### ISSUE THREAD

**Issue by Shayen** [hsoft/send2trash#30]
I try to use ```send2trash('file_path')``` but file still not move to my Recycle Bin with no any error message.

It's look like the issue came from ```get_short_path_name()```  because it return ```u''```
But when I bypass ```get_short_path_name()``` method, ```send2trash()``` seem working for me.

```python
def get_short_path_name(long_name):
    return long_name
    # if not long_name.startswith('\\\\?\\'):
    #     long_name = '\\\\?\\' + long_name
    # buf_size = GetShortPathNameW(long_name, None, 0)
    # output = create_unicode_buffer(buf_size)
    # GetShortPathNameW(long_name, output, buf_size)
    # return output.value[4:]  # Remove '\\?\' for SHFileOperationW
```

I'm using python 2.7.14 on Windows 10.0.16299 .

**Comment by BoboTiG** [comment]
Could you provide a path that is problematic ?

**Comment by Shayen** [comment]
Oh, Sorry.
my path is "C:/Users/user/WORK/project/textFile.txt"

**Comment by BoboTiG** [comment]
Perhaps slashes are the problem. What about `C:\\Users\\user\\WORK\\project\\textFile.txt`?

**Comment by BoboTiG** [comment]
Also, could you give us a real path with your username? There may be unicode things too.

**Comment by Shayen** [comment]
It's working perfectly with double slash :smiley:
```"C:\\Users\\nook\\WORK\\F18\\ZANDBOX\\SH0010\\LIGHTING\\backup.ma"``` (This is my real path)
And single slash should be support also. 

Thank you.

**Comment by BoboTiG** [comment]
You could use `os.path.abspath(path)` before sending to send2trash, it will normalize the slashes on the current OS.

**Comment by johnbolia** [comment]
I have this same problem. I am having to run `path.replace('/', '\\')` before using send2trash.  

`os.path.abspath(path)` will not work in many cases as it merely puts the `os.getcwd()` in front of the filename.

It seems that most other python modules handle either slash style or mixed strings. So it is surprising that it isn't. I am going to open a separate issue that send2trash 1.50 is failing silently in windows
