### ISSUE TITLE
send2trash 1.50 is failing silently in windows

### ISSUE THREAD

**Issue by johnbolia** [hsoft/send2trash#31]
I am running the latest send2trash 1.50 in python 3.6 in windows10. I can put any string into send2trash and it will work if the string is a valid filepath, if not it fails without an error message.

In Linux I receive:
`OSError: Error trashing file /home/anon/tennis.txt: No such file or directory`

**Comment by hsoft** [comment]
Thanks for the report. PR welcome. I don't have a Windows machine so I can't test any of this, but if the PR look good, I'll merge it.

**Comment by rkhwaja** [comment]
I checked on python 3.7.2 on windows 7. SHFileOperationW is returning 0, whereas it promises to return non-zero on failure - see https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shfileoperationw
You could do a pre-check that the file exists and throw OSError if so

**Comment by BoboTiG** [comment]
It should already be the case: see https://github.com/hsoft/send2trash/blob/020d05979d4f4e0040796062120819bbf3be973f/send2trash/plat_win.py#L85-L86

I do not think doing a pre-check is a good idea, the lighter the best.
But we can try to understand why the exception is not raised. Perhaps @johnbolia can you provide an example of a complete path that was not working?
