### ISSUE TITLE
Can't delete files with emoji in the name

### ISSUE THREAD

**Issue by Carnivalio** [hsoft/send2trash#37]
here's what error says:

>  File "C:\Users\Carnival\AppData\Local\Programs\Python\Python37\lib\site->packages\send2trash\plat_win.py", line 86, in send2trash
>    raise WindowsError(None, None, path, result)
>OSError: [WinError 87] None: '🆚.jpg'

also, sometimes it says file not found, for the same reason (emoji in the name)

Thank you

**Comment by BoboTiG** [comment]
Why did you close the issue?
